### ISSUE TITLE
Checklist for adding the SN cohort for revision

### ISSUE THREAD

**Issue by fsvarn** [fsvarn/GLASSx#17]
### Snakemake pipeline steps

**Alignment and quality control**
- [x]  align
- [x] fingerprint
- [x] gencode

**Somatic variant calling**
- [x] mutect
- [x] m2db

**Copy number calling**
- [x] cnv (gatk cnv)
- [x] titancna
- [x] sequenza

**Expression**
- [x] quant_tpm
- [x] tpm2db (manually run R function)
- [x] transcriptclass2db (manually run R function)
